name: mobxbasico
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  mobx: ^1.1.1
  flutter_mobx: ^1.1.0
  provider: ^4.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.1
  mobx_codegen: ^1.0.3

flutter:
  uses-material-design: true

