name: slidy01
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_modular:
  mobx:
  flutter_mobx:

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen:
  build_runner:

flutter:
  uses-material-design: true